### ISSUE TITLE
Add vue-breadcrumbs Topic to project

### ISSUE THREAD

**Issue by tinohager** [pratheekhegde/vue-dynamic-breadcrumbs#1]
Can you add the following topic to your project?

![image](https://user-images.githubusercontent.com/8215186/52563664-658c0c00-2e02-11e9-87e8-aa38d3f0c6c2.png)

**Comment by pratheekhegde** [comment]
Added. 😃 Any particular reason to add?

**Comment by tinohager** [comment]
It's much more easy to find all the available projects if the use the same topics 😄 

https://github.com/topics/vue-breadcrumbs
